---

# Fix ssh configuration that prevent root login with password.
- name: Fix ssh login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin .*'
    line: 'PermitRootLogin no'
    backrefs: yes
  notify: ssh restart

# Wait 3 minutes before sending a access deny for bad passwords.
# should be enough since default ssh LoginGraceTime is 120s.
- name: slow down bad ssh logins
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '^auth +required +pam_faildelay\.so.*'
    line: 'auth required pam_faildelay.so debug delay=180000000'
    insertbefore: ' Standard Un.x authentication.'
  when: ansible_system in [ 'Linux' ]
  notify: ssh restart                
